FORMAT: 1A
HOST: http://socialbattle-api.herokuapp.com

# SocialBattle
An fusion between a common social network and an RPG game

# Group User
## User [/users/{username}]
A single User object

+ Parameters
    + username (string) ... String representing the `username` of the User.

### Retrieve a user [GET]
+ Response 200 (application/json)
        
        {
            "url": "http://localhost:8000/users/sb_user/", 
            "username": "sb_user", 
            "email": "sb_user@sb.com", 
            "img": "http://www.gravatar.com/avatar/065328c818309bd7f18b4083fcbe656e?d=identicon", 
            "no_following": 0, 
            "no_followers": 0
        }



# Group Fellowship
## Fellowship [/fellowship/{id}]
### Retrieve a fellowship [GET]
+ Response 200 (application/json)

        {
            "url": "http://localhost:8000/fellowship/17/", 
            "from_user": "http://localhost:8000/users/another_sb_user/", 
            "to_user": "http://localhost:8000/users/sb_user/"
        }

### Delete a fellowship [DELETE]
+ Response 204

## User Following [/users/{username}/following]
The list of the users that a user is following

### List all following [GET]
+ Response 200 (application/json)

        [
            {
                "url": "http://localhost:8000/fellowship/7/", 
                "to_user": {
                    "url": "http://localhost:8000/users/another_sb_user/", 
                    "username": "another_sb_user", 
                    "email": "another_sb_user@sb.com", 
                    "img": "http://www.gravatar.com/avatar/60feaeae4ea163dedcd0f210281d7708?d=identicon", 
                    "no_following": 2, 
                    "no_followers": 1
                }
            }, 
            {
                "url": "http://localhost:8000/fellowship/9/", 
                "to_user": {
                    "url": "http://localhost:8000/users/someother_sb_user/", 
                    "username": "someother_sb_user", 
                    "email": "someother_sb_user@sb.com", 
                    "img": "http://www.gravatar.com/avatar/51d0e310ea1e05916620f126c078fcf1?d=identicon", 
                    "no_following": 0, 
                    "no_followers": 2
                }
            }
        ]

### Follow a user [POST]
+ Request (application/json)

        {
            "to_user": "http://socialbattle-api.herokuapp.com/users/another_sb_user"
        }

+ Response 201 (application/json)

        {
            "url": "http://localhost:8000/fellowship/1/", 
            "from_user": "http://localhost:8000/users/sb_user/", 
            "to_user": "http://localhost:8000/users/another_sb_user/"
        }

## User Followers [/users/{username}/followers]
The list of the users follows the specified user

### List all followers [GET]
+ Response 200 (application/json)

        [
            {
                "url": "http://localhost:8000/fellowship/17/", 
                "from_user": {
                    "url": "http://localhost:8000/users/another_sb_user/", 
                    "username": "another_sb_user", 
                    "email": "another_sb_user@sb.com", 
                    "img": "http://www.gravatar.com/avatar/60feaeae4ea163dedcd0f210281d7708?d=identicon", 
                    "no_following": 2, 
                    "no_followers": 1
                }
            }
        ]


#Group Room
## Relax Rooms [/rooms/relax]
All relax rooms
### List al relax rooms [GET]
+ Response 200 (application/json)

        [
            {
                "url": "http://localhost:8000/rooms/relax/moguri-shop/", 
                "name": "moguri shop", 
                "slug": "moguri-shop", 
                "fb_id": "716467545059393"
            }, 
            {
                "url": "http://localhost:8000/rooms/relax/chocobo-emporium/", 
                "name": "chocobo emporium", 
                "slug": "chocobo-emporium", 
                "fb_id": "245988905597076"
            }
        ]


## PVE Rooms [/rooms/pve]
All PVE rooms
### List al PVE rooms [GET]
+ Response 200 (application/json)

        [
            {
                "url": "http://localhost:8000/rooms/pve/zertinan-caves/", 
                "name": "zertinan caves", 
                "slug": "zertinan-caves", 
                "fb_id": "900462223304608"
            }, 
            {
                "url": "http://localhost:8000/rooms/pve/golmore-jungle/", 
                "name": "golmore jungle", 
                "slug": "golmore-jungle", 
                "fb_id": "1415747728712053"
            }
        ]

## All Rooms [/rooms]
### List all rooms independently from the type [GET]
+ Response 200 (application/json)

        [
            {
                "url": "http://localhost:8000/rooms/relax/chocobo-emporium/", 
                "name": "chocobo emporium", 
                "slug": "chocobo-emporium", 
                "fb_id": "245988905597076"
            }, 
            {
                "url": "http://localhost:8000/rooms/pve/zertinan-caves/", 
                "name": "zertinan caves", 
                "slug": "zertinan-caves", 
                "fb_id": "900462223304608"
            },
        ]


# Group Post
## User Posts [/user/{username}/posts]
All posts from the specified user

### List all posts [GET]
This resource uses paging, pages can explored using `previous` and `next` fields of the response.  
The number of resources returned can be limited using `?limit={integer}`.

+ Response 200 (application/json)

    {
        "count": 1, 
        "next": null, 
        "previous": null, 
        "results": [
            {
                "url": "http://localhost:8000/posts/8/", 
                "content": "Hello world Again!", 
                "author": {
                    "url": "http://localhost:8000/users/sb_user/", 
                    "username": "sb_user", 
                    "img": "http://www.gravatar.com/avatar/065328c818309bd7f18b4083fcbe656e?d=identicon"
                }, 
                "room": {
                    "url": "http://localhost:8000/rooms/relax/moguri-shop/", 
                    "name": "moguri shop", 
                    "slug": "moguri-shop"
                }, 
                "time": "2014-06-06T14:56:53Z"
            }
        ]
    }


